### ISSUE TITLE
autoprefixer not working

### ISSUE THREAD

**Issue by pipejesus** [JoeCianflone/laravel-elixir-sass-compass#10]
Is there a way to integrate Elixir's gulp-autoprefixer with laravel-elixir-sass-compass? The autoprefixer works fine when running mix.sass() but mix.compass() does not autoprefix . Hope somebody can help me out.

**Comment by JoeCianflone** [comment]
Old comment so I'm not sure if you solved this or not, but Compass already has built in vendor prefixing support so you don't need autoprefixer: http://compass-style.org/help/documentation/tuning-vendor-prefixes/
