### ISSUE TITLE
Import paths

### ISSUE THREAD

**Issue by jbrooksuk** [JoeCianflone/laravel-elixir-sass-compass#11]
Currently I have an import like this:

``` scss
@import "../bower_components/foundation/scss/foundation/_functions";
```

But I've since moved `bower_components` from `./resources/assets` (where the scss) folder was to `./vendor/`.

Why is `laravel-elixir-sass-compass` not able to use these paths?

**Comment by JoeCianflone** [comment]
Thinking you've just got an issue with your paths, if you have a specific error message you're getting I can take a look, but without an error that points specifically to the plugin I can't debug.
