### ISSUE TITLE
Invalid CSS issue

### ISSUE THREAD

**Issue by markaduffy** [JoeCianflone/laravel-elixir-sass-compass#12]
Can anyone help me with this? I dont know if this elixir specific.

I have output here http://pastebin.com/tfAXfAy1 and below 

gulp
[20:08:33] Using gulpfile /var/www/portal.app/gulpfile.js
[20:08:33] Starting 'default'...
[20:08:33] Starting 'compass'...
[20:08:33] Finished 'default' after 9.78 ms
    error resources/assets/scss/smartadmin/smartadmin-production-plugins.scss (Line 59 of resources/assets/scss/smartadmin/smartadmin/_plugin-bootstrap-markdown.scss: Invalid CSS after "...${color-rgba}")": expected "{", was ";")

```
error resources/assets/scss/smartadmin/smartadmin-production.scss (Line 23 of resources/assets/scss/smartadmin/smartadmin/_component-pace.scss: Invalid CSS after "  background: ": expected expression (e.g. 1px, bold), was "@blueStandard;")
```

Compilation failed in 2 files.

[20:08:34] gulp-notify: [Laravel Elixir] Compass Compilation Failed!:     error resources/assets/scss/smartadmin/smartadmin-production-plugins.scss (Line 59 of resources/assets/scss/smartadmin/smartadmin/_plugin-bootstrap-markdown.scss: Invalid CSS after "...${color-rgba}")": expected "{", was ";")
    error resources/assets/scss/smartadmin/smartadmin-production.scss (Line 23 of resources/assets/scss/smartadmin/smartadmin/_component-pace.scss: Invalid CSS after "  background: ": expected expression (e.g. 1px, bold), was "@blueStandard;")
Compilation failed in 2 files.

{ [Error:     error resources/assets/scss/smartadmin/smartadmin-production-plugins.scss (Line 59 of resources/assets/scss/smartadmin/smartadmin/_plugin-bootstrap-markdown.scss: Invalid CSS after "...${color-rgba}")": expected "{", was ";")
    error resources/assets/scss/smartadmin/smartadmin-production.scss (Line 23 of resources/assets/scss/smartadmin/smartadmin/_component-pace.scss: Invalid CSS after "  background: ": expected expression (e.g. 1px, bold), was "@blueStandard;")
Compilation failed in 2 files.
]
  message: '\u001b[31m    error\u001b[0m resources/assets/scss/smartadmin/smartadmin-production-plugins.scss (Line 59 of resources/assets/scss/smartadmin/smartadmin/_plugin-bootstrap-markdown.scss: Invalid CSS after "...${color-rgba}")": expected "{", was ";")\n\u001b[31m    error\u001b[0m resources/assets/scss/smartadmin/smartadmin-production.scss (Line 23 of resources/assets/scss/smartadmin/smartadmin/_component-pace.scss: Invalid CSS after "  background: ": expected expression (e.g. 1px, bold), was "@blueStandard;")\n\u001b[31mCompilation failed in 2 files.\n\u001b[0m',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function: bound ] } }
[20:08:34] 'compass' errored after 1.07 s
[20:08:34] Error in plugin 'gulp-compass'
Message:
        error resources/assets/scss/smartadmin/smartadmin-production-plugins.scss (Line 59 of resources/assets/scss/smartadmin/smartadmin/_plugin-bootstrap-markdown.scss: Invalid CSS after "...${color-rgba}")": expected "{", was ";")
    error resources/assets/scss/smartadmin/smartadmin-production.scss (Line 23 of resources/assets/scss/smartadmin/smartadmin/_component-pace.scss: Invalid CSS after "  background: ": expected expression (e.g. 1px, bold), was "@blueStandard;")
Compilation failed in 2 files.

[20:08:34] Error in plugin 'run-sequence'
Message:
    An error occured in task 'compass'.

**Comment by JoeCianflone** [comment]
Hi,
You have a bug in your code, this is not an issue with the plugin. The `@` symbol is used for variables in _Less_, in Sass you use `@` for things like `@include foo` or `@mixin foo()` not for variable names, which is what it looks like you're doing.
