### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'

### ISSUE THREAD

**Issue by barnabaskecskes** [JoeCianflone/laravel-elixir-sass-compass#13]
This package is not compatible with Laravel Elixir 3+. Can this be updated, please? See example at [this issue](https://github.com/peterreisz/laravel-elixir-ngtemplatecache/commit/4a67a3d176de8e00dab86c32a411137d22d73219) on how to fix it.

(I am in the middle of a refactoring and it would be nice if I could do it in steps. :) )

**Comment by JoeCianflone** [comment]
I can take a look at this but Compass has been deprecated. If you're doing a refactor you should consider _not_ using Compass.

**Comment by barnabaskecskes** [comment]
Hi @JoeCianflone and thanks. And yes, I will be removing Compass as well, but this is a bit of an ugly one here. I've got Susy, which depends on Compass, so I'd need to do a complete CSS refactoring as well. So in all, this is what I've meant by _would be nice if I could do it in steps_. :)

**Comment by JoeCianflone** [comment]
Susy no longer requires Compass. I've used it on multiple projects without Compass. 

I'll check this out tonight.

**Comment by JoeCianflone** [comment]
@barnabaskecskes can you post the error you're getting.

**Comment by barnabaskecskes** [comment]
<img width="946" alt="screen shot 2016-05-24 at 22 17 08" src="https://cloud.githubusercontent.com/assets/3535449/15520273/5b3acd18-21fd-11e6-90ba-1165c40ea97b.png">

**Comment by JoeCianflone** [comment]
Ah, it looks like you're running an older version of this plugin. Try updating the latest from NPM. This code is already compatible with Elixir 3.0 and the current version does not reference `Utilities`

**Comment by barnabaskecskes** [comment]
Gosh... how did I not notice that? Thanks, all works as expected! :)
