### ISSUE TITLE
Readme Config sass directory incorrect

### ISSUE THREAD

**Issue by chaosfinity** [JoeCianflone/laravel-elixir-sass-compass#4]
the default config for sass directory is

``` javascript
sass:        config.assetsDir + 'scss',
```

the readme shows

```
sass: "resources/assets/sass",
```

default looks for scss when I expected it to look for sass

**Comment by JoeCianflone** [comment]
Thanks for pointing that out, I've adjusted the readme.

**Comment by phaza** [comment]
Now it's defaulting to 'sass'. Fixed with `sass: "resources/assets/scss"`in config, but still annoying.

**Comment by chaosfinity** [comment]
Looks like now its using the laravel elixir config for the sass directory by default and not what is shown in the readme
