### ISSUE TITLE
Laravel Elixir 3 Compatibility

### ISSUE THREAD

**Issue by jbrooksuk** [JoeCianflone/laravel-elixir-sass-compass#5]

**Comment by ghost** [comment]
+1

**Comment by JoeCianflone** [comment]
@jbrooksuk I'll look into it, but can you give me a rundown on any particular issues you're seeing also, please don't add any +1 comments I'm going to work on this as soon as possible

**Comment by jbrooksuk** [comment]
@JoeCianflone a lot is broken, there is no ingredients code, the task isn't registered properly etc. I started looking into it on Saturday.

**Comment by JoeCianflone** [comment]
So Elixir 3 is basically a rewrite.  OK, so I'll look more into this this week and hopefully have something pushed out soon.

**Comment by jbrooksuk** [comment]
Tbh Elixir 2 didn't fully work either. I had to change the ingredients thing.

**Comment by liorocks** [comment]
@JoeCianflone Here's a example code of, how to (re)write extension for Elixir 3.X.

https://github.com/laravel/elixir/releases/tag/3.0.0

Maybe, this could help.

**Comment by fourstacks** [comment]
Hi all, have submitted a PR for this #6 - would be grateful for any feedback or bug spots.

Props to @Landish  for the link by the way - I'd have been scratching my head for far longer without that primer!

**Comment by JoeCianflone** [comment]
I've pushed an update to NPM thanks @FourStacks for creating the patch and @Landish for the info on the rewrite.

**Comment by fourstacks** [comment]
No worries - glad it's working for you! :+1:
